import type { JukeboxAppState } from "./jukeboxTypes";

const EMPTY_TRACK = {
  id: 0,
  title: "No track loaded",
  artist: "Unavailable",
  album: "Unavailable",
  duration: "0:00",
  coverUrl: "",
};

export const emptyJukeboxState: JukeboxAppState = {
  theme: "casual",
  connectionStatus: "connecting",
  media: {
    source: "local",
    sourceLabel: "Unavailable",
    spotifyConnected: false,
    isPlaying: false,
    progressPercent: 0,
    volumePercent: 0,
    activeTrackId: EMPTY_TRACK.id,
    activeTrack: EMPTY_TRACK,
    queue: [],
    audio: {
      quality: "Unavailable",
      codec: "Unavailable",
      bufferPercent: 0,
      dspProfile: "Flat",
    },
  },
  library: {
    songs: [],
    playlists: [],
  },
  telemetry: {
    presence: {
      confidencePercent: 0,
      reason: "Unavailable",
      distanceCm: 0,
      clapCountToday: 0,
      lastClapAt: "Unavailable",
      lastMode: "Unavailable",
    },
    voiceAssistant: {
      source: "Unavailable",
      command: "Unavailable",
      response: "Unavailable",
      updatedAt: "Unavailable",
    },
    distanceSeries: [],
    clapTrace: [],
    mqttFeed: [],
    eventLog: [],
    system: {
      mqttStatus: "Disconnected",
      mqttSecurity: "Not configured",
      uptime: "Unavailable",
      rssiDbm: "Unavailable",
      brokerLatency: "Unavailable",
      backendRuntime: {
        status: "unknown",
        service: "hajukebox-backend",
        updatedAt: null,
        mediaLibraryStatus: "unknown",
        mediaLibraryReason: null,
        haBridgeStatus: "unknown",
        haBridgeReason: null,
        lastSuccessfulPublishAt: null,
      },
    },
    automationLanes: [],
  },
  spotify: {
    configured: false,
    authStatus: "disconnected",
    sdkStatus: "idle",
    transferStatus: "idle",
    accountTier: "unknown",
    deviceId: null,
    deviceName: "Unavailable",
    isActiveDevice: false,
    lastError: null,
    currentTrack: null,
    positionMs: 0,
    durationMs: 0,
    scopes: [],
    expiresAt: null,
    mockMode: null,
  },
};
